/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.91 96/09/10 16:58:48 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)


#define YY_USES_REJECT
typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern int yylineno;
int yylineno = 1;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 82
#define YY_END_OF_BUFFER 83
static yyconst short int yy_acclist[296] =
    {   0,
       83,   81,   82,   80,   81,   82,   80,   82,   64,   81,
       82,   81,   82,   70,   81,   82,   63,   81,   82,   81,
       82,   78,   81,   82,   79,   81,   82,   68,   81,   82,
       67,   81,   82,   57,   81,   82,   66,   81,   82,   62,
       81,   82,   69,   81,   82,   25,   81,   82,   26,   81,
       82,   58,   81,   82,   56,   81,   82,   71,   81,   82,
       59,   81,   82,   72,   81,   82,   75,   81,   82,   23,
       81,   82,   23,   81,   82,   60,   81,   82,   61,   81,
       82,   73,   81,   82,   23,   81,   82,   23,   81,   82,
       23,   81,   82,   23,   81,   82,   23,   81,   82,   23,

       81,   82,   23,   81,   82,   23,   81,   82,   23,   81,
       82,   23,   81,   82,   23,   81,   82,   23,   81,   82,
       76,   81,   82,   74,   81,   82,   77,   81,   82,   65,
       81,   82,   55,   34,   41,   50,   42,   39,   47,   37,
       48,   38,   49,   29,    3,    1,    4,   40,   30,   25,
       25,   25,   25,   26,   26,   26,   26,   46,   52,   54,
       53,   45,   23,   43,   23,   23,   23,   23,   23,   12,
       23,   23,   23,   23,   23,   16,   23,   23,   23,   23,
       23,   23,   23,   44,   51,   27,   29,    1,    4,   29,
       30,   30,   28,   25,   25,   25,   25,   24,   26,   26,

       26,   26,   36,   35,   23,   23,   23,   23,   23,   23,
       23,   23,   14,   23,   23,    6,   23,   23,   23,   23,
       23,   23,   29,    2,   29,   30,   30,   28,   25,   32,
       33,   24,   24,   24,   26,    5,   23,   23,   10,   23,
        7,   23,   23,   23,   13,   23,   23,   15,   23,   23,
       23,   21,   23,   19,   23,   23,   29,   30,   32,   32,
       33,   33,   24,   24,   31,   24,   24,    9,   23,   23,
       23,   22,   23,   23,   23,   20,   23,   32,   32,   33,
       33,   31,   24,   23,    8,   23,   17,   23,   18,   23,
       32,   33,   23,   11,   23

    } ;

static yyconst short int yy_accept[216] =
    {   0,
        1,    1,    1,    2,    4,    7,    9,   12,   14,   17,
       20,   22,   25,   28,   31,   34,   37,   40,   43,   46,
       49,   52,   55,   58,   61,   64,   67,   70,   73,   76,
       79,   82,   85,   88,   91,   94,   97,  100,  103,  106,
      109,  112,  115,  118,  121,  124,  127,  130,  133,  134,
      134,  135,  135,  136,  137,  138,  138,  138,  139,  140,
      141,  142,  143,  144,  145,  146,  148,  149,  150,  151,
      151,  151,  152,  153,  153,  154,  155,  156,  157,  158,
      159,  160,  161,  162,  163,  164,  164,  164,  165,  166,
      167,  168,  169,  170,  172,  173,  174,  175,  176,  178,

      179,  180,  181,  182,  183,  184,  185,  186,  187,  187,
      188,  188,  188,  188,  190,  192,  192,  193,  193,  194,
      195,  196,  197,  198,  198,  199,  200,  201,  202,  203,
      204,  205,  206,  207,  208,  209,  210,  211,  212,  213,
      215,  216,  218,  219,  220,  221,  222,  223,  223,  224,
      225,  225,  227,  227,  228,  229,  230,  231,  232,  233,
      233,  234,  235,  236,  238,  239,  241,  243,  244,  245,
      247,  248,  250,  251,  252,  254,  256,  257,  257,  259,
      260,  260,  262,  263,  263,  264,  265,  265,  266,  267,
      268,  270,  271,  272,  274,  275,  276,  278,  278,  279,

      281,  281,  281,  282,  283,  284,  285,  287,  289,  291,
      291,  293,  294,  296,  296
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        2,    2,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    4,    5,    1,    1,    6,    7,    8,    9,
       10,   11,   12,   13,   14,   15,   16,   17,   18,   18,
       18,   18,   18,   18,   18,   19,   19,   20,   21,   22,
       23,   24,   25,    1,   26,   26,   26,   26,   27,   28,
       29,   29,   29,   29,   29,   30,   29,   29,   29,   31,
       29,   29,   29,   29,   32,   29,   29,   33,   29,   29,
       34,   35,   36,   37,   29,    1,   38,   39,   40,   41,

       42,   43,   44,   45,   46,   29,   47,   48,   29,   49,
       50,   31,   29,   51,   52,   53,   54,   55,   56,   33,
       29,   29,   57,   58,   59,   60,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[61] =
    {   0,
        1,    1,    2,    1,    1,    1,    1,    3,    1,    1,
        1,    1,    1,    1,    4,    1,    5,    5,    5,    1,
        1,    1,    1,    1,    1,    5,    5,    5,    6,    7,
        7,    6,    6,    1,    1,    1,    1,    5,    5,    5,
        5,    5,    5,    6,    6,    6,    6,    7,    6,    6,
        6,    6,    6,    6,    6,    6,    1,    1,    1,    1
    } ;

static yyconst short int yy_base[224] =
    {   0,
        0,    0,  434,  435,  435,  435,  410,   56,  409,   55,
      396,  435,  435,  407,   51,  435,   52,   50,   54,   77,
      117,  435,  435,   49,  405,   56,  435,    0,   76,  435,
      435,  389,   32,   48,  346,  347,   35,  338,   54,  343,
      328,  332,  332,  335,  435,   41,  435,  435,  435,   82,
      435,    0,  435,  435,  435,   80,  371,  435,  435,  435,
      435,  435,  435,  110,   89,    0,  435,  145,  344,  103,
       94,   94,   93,  361,  107,    0,  124,  103,  128,  352,
      435,  435,  435,  351,    0,  111,  337,  435,  321,  328,
      317,  329,  316,  310,  311,  314,  310,  306,    0,  297,

      291,  293,  284,  288,  283,  435,  435,  435,  167,  435,
      158,  178,  179,    0,  179,  196,  435,  149,  200,  138,
      435,  298,  278,    0,  201,  145,  435,  294,  275,  435,
      435,  264,  269,  263,  252,  249,  259,  244,  233,    0,
      220,    0,  200,  199,  208,  205,  196,  183,  217,  435,
      239,  435,  186,  244,  435,  435,  181,  193,  210,  259,
      190,  227,  435,    0,  192,    0,    0,  191,  178,    0,
      183,    0,  140,  143,    0,    0,  138,  249,  265,  435,
      282,  249,  435,  292,  237,  435,  271,  297,  127,  102,
        0,   94,  100,    0,   65,   57,    0,  300,  303,  435,

      318,  324,  330,  435,  435,   47,    0,    0,    0,  335,
      338,   48,    0,  435,  386,  393,  396,  403,  410,  414,
      419,   84,  422
    } ;

static yyconst short int yy_def[224] =
    {   0,
      214,    1,  214,  214,  214,  214,  214,  215,  214,  214,
      216,  214,  214,  214,  214,  214,  214,  214,  214,  214,
      214,  214,  214,  214,  214,  214,  214,  217,  217,  214,
      214,  214,  217,  217,  217,  217,  217,  217,  217,  217,
      217,  217,  217,  217,  214,  214,  214,  214,  214,  215,
      214,  215,  214,  214,  214,  216,  216,  214,  214,  214,
      214,  214,  214,  214,  218,  219,  214,  214,   20,  214,
      214,  214,  214,  220,  214,   21,  214,  214,  214,  214,
      214,  214,  214,  214,  217,  215,  216,  214,  217,  217,
      217,  217,  217,  217,  217,  217,  217,  217,  217,  217,

      217,  217,  217,  217,  217,  214,  214,  214,  214,  214,
      218,  221,  218,  219,  214,  214,  214,  214,  214,  214,
      214,  214,  214,  222,  220,  214,  214,  214,  214,  214,
      214,  217,  217,  217,  217,  217,  217,  217,  217,  217,
      217,  217,  217,  217,  217,  217,  217,  214,  214,  214,
      214,  214,  214,  214,  214,  214,  222,  223,  214,  214,
      214,  214,  214,  217,  217,  217,  217,  217,  217,  217,
      217,  217,  217,  217,  217,  217,  217,  214,  214,  214,
      214,  223,  214,  214,  214,  214,  214,  214,  214,  214,
      217,  217,  217,  217,  217,  217,  217,  214,  214,  214,

      214,  214,  214,  214,  214,  217,  217,  217,  217,  214,
      214,  217,  217,    0,  214,  214,  214,  214,  214,  214,
      214,  214,  214
    } ;

static yyconst short int yy_nxt[496] =
    {   0,
        4,    5,    6,    7,    8,    9,   10,   11,   12,   13,
       14,   15,   16,   17,   18,   19,   20,   21,   21,   22,
       23,   24,   25,   26,   27,   28,   28,   28,   28,   29,
       28,   28,   28,   30,    4,   31,   32,   28,   33,   34,
       35,   36,   37,   38,   28,   39,   28,   28,   28,   28,
       40,   41,   42,   28,   43,   44,   45,   46,   47,   48,
       51,   54,   59,  106,   65,   61,   64,   64,   64,   66,
       80,   81,   96,   60,   62,   63,   67,   55,   83,   84,
       86,   89,   90,   87,   97,   91,   51,  108,  157,  213,
       52,   68,   92,   69,   69,   70,   99,   93,  107,  112,

      212,  209,  100,   71,  113,  118,   72,  118,   73,   74,
      119,  119,  119,  208,   57,   51,   52,   68,   71,   70,
       70,   70,  122,  120,   75,  121,   64,   64,   64,   71,
       73,   68,  128,   76,   76,   76,  109,  110,  121,  110,
      123,  207,  206,   71,   71,   52,   77,  121,   78,  205,
      129,  109,  110,  126,  120,  127,  205,  110,   71,  127,
      121,  115,  115,  115,   79,  119,  119,  119,  112,  121,
       78,  116,  117,  113,  117,  126,  127,  127,  148,  197,
      148,  127,  196,  149,  149,  149,  116,  117,  112,  112,
      195,  121,  117,  150,  113,  115,  115,  115,  127,  149,

      149,  149,  154,  154,  154,  151,  152,  153,  152,  153,
      180,  181,  154,  154,  154,  158,  119,  119,  119,  189,
      151,  152,  183,  184,  194,  193,  152,  155,  180,  155,
      159,  160,  161,  149,  149,  149,  192,  190,  191,  185,
      183,  186,  155,  177,  110,  176,  110,  155,  162,  175,
      178,  174,  178,  173,  161,  179,  179,  179,  186,  110,
      154,  154,  154,  186,  110,  179,  179,  179,  186,  172,
      187,  117,  187,  117,  185,  188,  188,  188,  200,  201,
      186,  179,  179,  179,  171,  170,  117,  188,  188,  188,
      186,  117,  152,  198,  152,  198,  200,  169,  199,  199,

      199,  168,  167,  202,  166,  202,  165,  152,  203,  203,
      203,  164,  152,  188,  188,  188,  199,  199,  199,  199,
      199,  199,  163,  163,  204,  156,  204,  156,  147,  210,
      180,  210,  180,  146,  211,  211,  211,  145,  144,  204,
      203,  203,  203,  143,  204,  180,  203,  203,  203,  142,
      180,  211,  211,  211,  211,  211,  211,  183,  141,  183,
      140,  139,  138,  137,  136,  200,  135,  200,  134,  133,
      132,   57,  183,  131,  130,  124,  214,  183,   56,  105,
      200,  104,  103,  102,  101,  200,   50,   98,   50,   50,
       50,   50,   50,   56,   95,   94,   56,   56,   56,   56,

       85,   85,   85,  111,  111,  111,  111,  111,  111,  111,
      114,   88,  114,  114,  114,  114,  114,  125,  125,  113,
      113,  113,  113,  113,  113,  113,  182,   82,  182,   58,
       57,   53,   49,  214,    3,  214,  214,  214,  214,  214,
      214,  214,  214,  214,  214,  214,  214,  214,  214,  214,
      214,  214,  214,  214,  214,  214,  214,  214,  214,  214,
      214,  214,  214,  214,  214,  214,  214,  214,  214,  214,
      214,  214,  214,  214,  214,  214,  214,  214,  214,  214,
      214,  214,  214,  214,  214,  214,  214,  214,  214,  214,
      214,  214,  214,  214,  214

    } ;

static yyconst short int yy_chk[496] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        8,   10,   15,   46,   19,   17,   18,   18,   18,   19,
       24,   24,   37,   15,   17,   17,   19,   10,   26,   26,
       29,   33,   33,   29,   37,   34,   50,   56,  222,  212,
        8,   20,   34,   20,   20,   20,   39,   34,   46,   65,

      206,  196,   39,   20,   65,   71,   20,   71,   20,   20,
       71,   71,   71,  195,   56,   86,   50,   70,   20,   70,
       70,   70,   73,   72,   20,   72,   64,   64,   64,   70,
       20,   21,   78,   21,   21,   21,   64,   64,   75,   64,
       73,  193,  192,   21,   70,   86,   21,   72,   21,  190,
       78,   64,   64,   77,   75,   77,  189,   64,   21,   79,
       75,   68,   68,   68,   21,  118,  118,  118,  111,  120,
       21,   68,   68,  111,   68,   79,  126,   77,  109,  177,
      109,   79,  174,  109,  109,  109,   68,   68,  112,  113,
      173,  120,   68,  112,  113,  115,  115,  115,  126,  148,

      148,  148,  153,  153,  153,  115,  115,  116,  115,  116,
      157,  157,  116,  116,  116,  125,  119,  119,  119,  161,
      115,  115,  158,  158,  171,  169,  115,  119,  157,  119,
      125,  125,  125,  149,  149,  149,  168,  161,  165,  159,
      158,  159,  119,  147,  149,  146,  149,  119,  125,  145,
      151,  144,  151,  143,  125,  151,  151,  151,  162,  149,
      154,  154,  154,  159,  149,  178,  178,  178,  185,  141,
      160,  154,  160,  154,  162,  160,  160,  160,  182,  182,
      162,  179,  179,  179,  139,  138,  154,  187,  187,  187,
      185,  154,  179,  181,  179,  181,  182,  137,  181,  181,

      181,  136,  135,  184,  134,  184,  133,  179,  184,  184,
      184,  132,  179,  188,  188,  188,  198,  198,  198,  199,
      199,  199,  129,  128,  188,  123,  188,  122,  105,  201,
      199,  201,  199,  104,  201,  201,  201,  103,  102,  188,
      202,  202,  202,  101,  188,  199,  203,  203,  203,  100,
      199,  210,  210,  210,  211,  211,  211,  203,   98,  203,
       97,   96,   95,   94,   93,  211,   92,  211,   91,   90,
       89,   87,  203,   84,   80,   74,   69,  203,   57,   44,
      211,   43,   42,   41,   40,  211,  215,   38,  215,  215,
      215,  215,  215,  216,   36,   35,  216,  216,  216,  216,

      217,  217,  217,  218,  218,  218,  218,  218,  218,  218,
      219,   32,  219,  219,  219,  219,  219,  220,  220,  221,
      221,  221,  221,  221,  221,  221,  223,   25,  223,   14,
       11,    9,    7,    3,  214,  214,  214,  214,  214,  214,
      214,  214,  214,  214,  214,  214,  214,  214,  214,  214,
      214,  214,  214,  214,  214,  214,  214,  214,  214,  214,
      214,  214,  214,  214,  214,  214,  214,  214,  214,  214,
      214,  214,  214,  214,  214,  214,  214,  214,  214,  214,
      214,  214,  214,  214,  214,  214,  214,  214,  214,  214,
      214,  214,  214,  214,  214

    } ;

static yy_state_type yy_state_buf[YY_BUF_SIZE + 2], *yy_state_ptr;
static char *yy_full_match;
static int yy_lp;
#define REJECT \
{ \
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */ \
yy_cp = yy_full_match; /* restore poss. backed-over text */ \
++yy_lp; \
goto find_rule; \
}
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "compiler.l"
#define INITIAL 0
#line 3 "compiler.l"
#include "y.tab.h"
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include "tree.h"
#include "Praser.h"
#include <iostream>
using namespace std;

void count(void);
void comment();
int check_type();
int column = 0;

#line 606 "lex.yy.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 29 "compiler.l"

#line 759 "lex.yy.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
		yy_state_ptr = yy_state_buf;
		*yy_state_ptr++ = yy_current_state;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 215 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			*yy_state_ptr++ = yy_current_state;
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 435 );

yy_find_action:
		yy_current_state = *--yy_state_ptr;
		yy_lp = yy_accept[yy_current_state];
find_rule: /* we branch to this label when backing up */
		for ( ; ; ) /* until we find what rule we matched */
			{
			if ( yy_lp && yy_lp < yy_accept[yy_current_state + 1] )
				{
				yy_act = yy_acclist[yy_lp];
					{
					yy_full_match = yy_cp;
					break;
					}
				}
			--yy_cp;
			yy_current_state = *--yy_state_ptr;
			yy_lp = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					++yylineno;
			}

do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
case 1:
YY_RULE_SETUP
#line 30 "compiler.l"
{printf("comment");}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 31 "compiler.l"
{}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 32 "compiler.l"
{ comment();/*注释*/}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 33 "compiler.l"
{ /* consume //-comment */ }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 35 "compiler.l"
{ count(); yylval.gt =create_tree("BOOL",0,yylineno); 		return(BOOL);	}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 36 "compiler.l"
{ count(); yylval.gt =create_tree("INT",0,yylineno);  		return(INT); }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 37 "compiler.l"
{ count(); yylval.gt =create_tree("CHAR",0,yylineno); 		return(CHAR); }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 38 "compiler.l"
{ count(); yylval.gt =create_tree("DOUBLE",0,yylineno); 	return(DOUBLE); }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 39 "compiler.l"
{ count(); yylval.gt =create_tree("BREAK",0,yylineno); 		return(BREAK); }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 40 "compiler.l"
{ count(); yylval.gt =create_tree("CASE",0,yylineno); 		return(CASE); }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 41 "compiler.l"
{ count(); yylval.gt =create_tree("CONTINUE",0,yylineno); 	return(CONTINUE); }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 42 "compiler.l"
{ count(); yylval.gt =create_tree("DO",0,yylineno);			return(DO); }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 43 "compiler.l"
{ count(); yylval.gt =create_tree("ELSE",0,yylineno);		return(ELSE); }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 44 "compiler.l"
{ count(); yylval.gt =create_tree("FOR",0,yylineno);		return(FOR); }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 45 "compiler.l"
{ count(); yylval.gt =create_tree("GOTO",0,yylineno);		return(GOTO); }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 46 "compiler.l"
{ count(); yylval.gt =create_tree("IF",0,yylineno);			return(IF); }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 47 "compiler.l"
{ count(); yylval.gt =create_tree("RETURN",0,yylineno);		return(RETURN); }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 48 "compiler.l"
{ count(); yylval.gt =create_tree("SWITCH",0,yylineno);		return(SWITCH); }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 49 "compiler.l"
{ count(); yylval.gt =create_tree("VOID",0,yylineno);		return(VOID); }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 50 "compiler.l"
{ count(); yylval.gt =create_tree("WHILE",0,yylineno);		return(WHILE); }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 51 "compiler.l"
{ count(); yylval.gt =create_tree("TRUE",0,yylineno);		return(TRUE); }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 52 "compiler.l"
{ count(); yylval.gt =create_tree("FALSE",0,yylineno);		return(FALSE); }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 54 "compiler.l"
{count(); yylval.gt =create_tree("IDENTIFIER",0,yylineno);	return(check_type());/*IDENTIFIER*/ }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 56 "compiler.l"
{ count(); yylval.gt =create_tree("CONSTANT_INT",0,yylineno);	return(CONSTANT_INT); /*16进制*/}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 57 "compiler.l"
{ count(); yylval.gt =create_tree("CONSTANT_INT",0,yylineno);	return(CONSTANT_INT); /*8进制*/}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 58 "compiler.l"
{ count(); yylval.gt =create_tree("CONSTANT_INT",0,yylineno);	return(CONSTANT_INT); /*10进制*/}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 59 "compiler.l"
{ count(); return(CONSTANT); }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 61 "compiler.l"
{ count(); yylval.gt =create_tree("CONSTANT_DOUBLE",0,yylineno);	return(CONSTANT_DOUBLE); /*浮点数*/}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 62 "compiler.l"
{ count(); yylval.gt =create_tree("CONSTANT_DOUBLE",0,yylineno);	return(CONSTANT_DOUBLE); /*浮点数*/}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 63 "compiler.l"
{ count(); yylval.gt =create_tree("CONSTANT_DOUBLE",0,yylineno);	return(CONSTANT_DOUBLE); /*浮点数*/}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 64 "compiler.l"
{ count(); return(CONSTANT); }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 65 "compiler.l"
{ count(); return(CONSTANT); }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 66 "compiler.l"
{ count(); return(CONSTANT); }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 69 "compiler.l"
{ count();  yylval.gt =create_tree("STRING_LITERAL",0,yylineno);	return(STRING_LITERAL); /*字符串常量*/}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 71 "compiler.l"
{ count(); yylval.gt =create_tree("RIGHT_ASSIGN",0,yylineno);	return(RIGHT_ASSIGN); }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 72 "compiler.l"
{ count(); yylval.gt =create_tree("LEFT_ASSIGN",0,yylineno);	return(LEFT_ASSIGN); }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 73 "compiler.l"
{ count(); yylval.gt =create_tree("ADD_ASSIGN",0,yylineno);		return(ADD_ASSIGN); }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 74 "compiler.l"
{ count(); yylval.gt =create_tree("SUB_ASSIGN",0,yylineno);		return(SUB_ASSIGN); }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 75 "compiler.l"
{ count(); yylval.gt =create_tree("MUL_ASSIGN",0,yylineno);		return(MUL_ASSIGN); }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 76 "compiler.l"
{ count(); yylval.gt =create_tree("DIV_ASSIGN",0,yylineno);		return(DIV_ASSIGN); }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 77 "compiler.l"
{ count(); yylval.gt =create_tree("MOD_ASSIGN",0,yylineno);		return(MOD_ASSIGN); }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 78 "compiler.l"
{ count(); yylval.gt =create_tree("AND_ASSIGN",0,yylineno);		return(AND_ASSIGN); }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 79 "compiler.l"
{ count(); yylval.gt =create_tree("XOR_ASSIGN",0,yylineno);		return(XOR_ASSIGN); }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 80 "compiler.l"
{ count(); yylval.gt =create_tree("OR_ASSIGN",0,yylineno);		return(OR_ASSIGN); }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 81 "compiler.l"
{ count(); yylval.gt =create_tree("RIGHT_OP",0,yylineno);		return(RIGHT_OP); }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 82 "compiler.l"
{ count(); yylval.gt =create_tree("LEFT_OP",0,yylineno);		return(LEFT_OP); }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 83 "compiler.l"
{ count(); yylval.gt =create_tree("INC_OP",0,yylineno);			return(INC_OP); }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 84 "compiler.l"
{ count(); yylval.gt =create_tree("DEC_OP",0,yylineno);			return(DEC_OP); }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 85 "compiler.l"
{ count(); yylval.gt =create_tree("PTR_OP",0,yylineno);			return(PTR_OP); }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 86 "compiler.l"
{ count(); yylval.gt =create_tree("AND_OP",0,yylineno);			return(AND_OP); }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 87 "compiler.l"
{ count(); yylval.gt =create_tree("OR_OP",0,yylineno);			return(OR_OP); }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 88 "compiler.l"
{ count(); yylval.gt =create_tree("LE_OP",0,yylineno);			return(LE_OP); }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 89 "compiler.l"
{ count(); yylval.gt =create_tree("GE_OP",0,yylineno);			return(GE_OP); }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 90 "compiler.l"
{ count(); yylval.gt =create_tree("EQ_OP",0,yylineno);			return(EQ_OP); }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 91 "compiler.l"
{ count(); yylval.gt =create_tree("NE_OP",0,yylineno);			return(NE_OP); }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 92 "compiler.l"
{ count(); yylval.gt =create_tree(";",0,yylineno);	return(';'); }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 93 "compiler.l"
{ count(); yylval.gt =create_tree(",",0,yylineno);	return(','); }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 94 "compiler.l"
{ count(); yylval.gt =create_tree(":",0,yylineno);	return(':'); }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 95 "compiler.l"
{ count(); yylval.gt =create_tree("=",0,yylineno);	return('='); }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 96 "compiler.l"
{ count(); yylval.gt =create_tree("[",0,yylineno);	return('['); }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 97 "compiler.l"
{ count(); yylval.gt =create_tree("]",0,yylineno);	return(']'); }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 98 "compiler.l"
{ count(); yylval.gt =create_tree(".",0,yylineno);	return('.'); }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 99 "compiler.l"
{ count(); yylval.gt =create_tree("&",0,yylineno);	return('&'); }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 100 "compiler.l"
{ count(); yylval.gt =create_tree("!",0,yylineno);	return('!'); }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 101 "compiler.l"
{ count(); yylval.gt =create_tree("~",0,yylineno);	return('~'); }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 102 "compiler.l"
{ count(); yylval.gt =create_tree("-",0,yylineno);	return('-'); }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 103 "compiler.l"
{ count(); yylval.gt =create_tree("+",0,yylineno);	return('+'); }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 104 "compiler.l"
{ count(); yylval.gt =create_tree("*",0,yylineno);	return('*'); }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 105 "compiler.l"
{ count(); yylval.gt =create_tree("/",0,yylineno);	return('/'); }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 106 "compiler.l"
{ count(); yylval.gt =create_tree("%",0,yylineno);	return('%'); }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 107 "compiler.l"
{ count(); yylval.gt =create_tree("<",0,yylineno);	return('<'); }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 108 "compiler.l"
{ count(); yylval.gt =create_tree(">",0,yylineno);	return('>'); }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 109 "compiler.l"
{ count(); yylval.gt =create_tree("^",0,yylineno);	return('^'); }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 110 "compiler.l"
{ count(); yylval.gt =create_tree("|",0,yylineno);	return('|'); }
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 111 "compiler.l"
{ count(); yylval.gt =create_tree("?",0,yylineno);	return('?'); }
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 112 "compiler.l"
{ count(); yylval.gt =create_tree("{",0,yylineno);	return('{'); }
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 113 "compiler.l"
{ count(); yylval.gt =create_tree("}",0,yylineno);	return('}'); }
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 114 "compiler.l"
{ count(); yylval.gt =create_tree("(",0,yylineno);	return('('); }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 115 "compiler.l"
{ count(); yylval.gt =create_tree(")",0,yylineno);	return(')'); }
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 117 "compiler.l"
{ count();}
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 118 "compiler.l"
{ /* Add code to complain about unmatched characters */ }
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 120 "compiler.l"
ECHO;
	YY_BREAK
#line 1260 "lex.yy.c"
			case YY_STATE_EOF(INITIAL):
				yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;
	yy_state_ptr = yy_state_buf;
	*yy_state_ptr++ = yy_current_state;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 215 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		*yy_state_ptr++ = yy_current_state;
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;

	register YY_CHAR yy_c = 1;
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 215 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 214);
	if ( ! yy_is_jam )
		*yy_state_ptr++ = yy_current_state;

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	if ( c == '\n' )
		--yylineno;

	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;

	if ( c == '\n' )
		++yylineno;

	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 120 "compiler.l"



int yywrap() {
	return 1;
}


void comment() {
	column = 0;
	char c, prev = 0;
	
	while (cin >> c)      /* (EOF maps to 0) */
	{
		if (c == '/' && prev == '*')
			return;
		prev = c;
	}
	printf("unterminated comment");
}



void count(void)
{
	int i;

	for (i = 0; yytext[i] != '\0'; i++)
		if (yytext[i] == '\n')
			column = 0;
		else if (yytext[i] == '\t')
			column += 4 - (column % 4);
		else
			column++;
	ECHO;
}


int check_type() {
/*
* pseudo code --- this is what it should check
*
*	if (yytext == type_name)
*		return TYPE_NAME;
*
*	return IDENTIFIER;
*/

/*
*	it actually will only return IDENTIFIER
*/

	return IDENTIFIER;
}